#!/bin/bash

######################################################################
#
#  Copyright (c) 2017 revosftw (https://github.com/revosftw)
#
######################################################################

install_gnome_minimal(){
  print_title "GNOME - https://wiki.archlinux.org/index.php/GNOME"
  print_info "GNOME is a desktop environment and graphical user interface that runs on top of a computer operating system. It is composed entirely of free and open source software. It is an international project that includes creating software development frameworks, selecting application software for the desktop, and working on the programs that manage application launching, file handling, and window and task management."
  package_install "gnome gnome-extra gnome-software gnome-initial-setup"
  package_install "deja-dup gedit-plugins gpaste gnome-tweak-tool gnome-power-manager"
  package_install "nautilus-share"
  # remove gnome games
  package_remove "aisleriot atomix four-in-a-row five-or-more gnome-2048 gnome-chess gnome-klotski gnome-mahjongg gnome-mines gnome-nibbles gnome-robots gnome-sudoku gnome-tetravex gnome-taquin swell-foop hitori iagno quadrapassel lightsoff tali"
  # config xinitrc
  config_xinitrc "gnome-session"
  GNOME=1
  pause_function
  install_themes "GNOME"
  #Gnome Display Manager (a reimplementation of xdm)
  system_ctl enable gdm
}
