#!/bin/bash

######################################################################
#
#  Copyright (c) 2019 revosftw (https://github.com/revosftw)
#
######################################################################

install_budgie_desktop(){
  print_title "BUDGIE - https://wiki.archlinux.org/index.php/Budgie_Desktop"
  print_info "Budgie is the default desktop of Solus Operating System, written from scratch. Besides a more modern design, Budgie can emulate the look and feel of the GNOME 2 desktop."
  package_install "gnome gnome-extra gnome-software gnome-initial-setup telepathy"
  package_install "deja-dup gedit-plugins gpaste gnome-tweak-tool gnome-power-manager"
  package_install "budgie-desktop"
  package_install "nautilus-share"
  # remove gnome games
  package_remove "aisleriot atomix four-in-a-row five-or-more gnome-2048 gnome-chess gnome-klotski gnome-mahjongg gnome-mines gnome-nibbles gnome-robots gnome-sudoku gnome-tetravex gnome-taquin swell-foop hitori iagno quadrapassel lightsoff"
  # config xinitrc
  config_xinitrc "export XDG_CURRENT_DESKTOP=Budgie:GNOME \n budgie-desktop"
  GNOME=1
  pause_function
  install_themes "GNOME"
  #Gnome Display Manager (a reimplementation of xdm)
  system_ctl enable gdm
}
