#!/bin/sh

######################################################################
#
#  Copyright (c) 2017 revosftw (https://github.com/revosftw)
#
######################################################################


###############################
### SET VARIABLES ###
###############################

pkgname=yaourt
aur=https://aur.archlinux.org/yaourt.git
package-query
###############################
### FUNCTIONS ###
###############################

install_aur(){
	cd /tmp
	git clone https://aur.archlinux.org/yaourt.git
	cd yaourt/
	makepkg -si
	cd ..
	rm -rf yaourt
}
