#!/bin/sh

######################################################################
#
#  Copyright (c) 2019 revosftw (https://github.com/revosftw)
#
######################################################################


###############################
### SET VARIABLES ###
###############################

pkgname=package-query
aur=https://aur.archlinux.org/package-query.git

###############################
### FUNCTIONS ###
###############################

install_aur(){
	cd /tmp
	git clone ${aur}
	cd ${pkgname}/
	makepkg -si
	cd ..
	rm -rf ${pkgname}
}
